Multiline command

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -24,5 +24,9 @@ publish:
   tags:
     - bsg
   script:
-      - if [ -z "$CI_RELEASE_TAG"]; then echo "Error: Please set CI_RELEASE_TAG"; exit 1; fi
+      - >
+        if [ "z$CI_RELEASE_TAG" == "z"]; then
+          echo "Error: Please set CI_RELEASE_TAG";
+          exit 1;
+        fi
       - echo "$CI_RELEASE_TAG"
